all:
  children:
    ungrouped: {
      }
    consul_existing_servers:
      hosts:
        192.168.19.196: {
          }
    consul_instances:
      hosts:
        192.168.19.207:
          consul_node_role: client
