all:
  children:
    nomad_existing_servers:
      hosts:
        192.168.19.196: {
          }
    nomad_instances:
      hosts:
        192.168.19.92:
          nomad_node_role: client
    ungrouped: {
      }
